Task1 graph
Lsr248/formal-lang-course pull request #1
Opened 2023-02-26 19:42 UTC by Lsr248

2023-03-01 14:29 UTC, rustam-azimov requested changes
В будущем поздний запрос ревью или необходимость исправлений после дедлайна будут штрафоваться баллами.

2023-03-01 14:29 UTC, rustam-azimov commented on project/graphUtils.py
> +        graph.number_of_nodes(),
Лучше использовать named tuple.

2023-03-05 13:22 UTC, Lsr248 commented
Спасибо! Больше не буду забывать добавить в ревью!
Использовала namedtuple и в функции get_graph_info

2023-03-05 14:45 UTC, rustam-azimov approved these changes

2023-05-15 12:24 UTC, merged