Homework_task6
Lsr248/formal-lang-course pull request #4
Opened 2023-04-03 16:54 UTC by Lsr248

Сделала задание номер 6

2023-04-07 13:45 UTC, rustam-azimov requested changes

2023-04-07 13:45 UTC, rustam-azimov commented on project/cnfUtils.py
> +        cfg.remove_useless_symbols()
Эту строку можно убрать.

2023-05-15 11:25 UTC, Lsr248 commented
Внесла исправления, убрала строку

2023-05-20 11:48 UTC, rustam-azimov approved these changes

2023-06-19 15:11 UTC, merged