Homework_task8
Lsr248/formal-lang-course pull request #6
Opened 2023-04-17 19:09 UTC by Lsr248

2023-04-18 09:50 UTC, rustam-azimov requested changes
Я правильно понимаю, что проверять тут надо только задание 8?

2023-04-18 09:50 UTC, rustam-azimov commented on project/hellings.py
> +def hellings(graph: Graph, cfg: CFG) -> set:
Добавьте док стринги и предусмотрите возможность передавать граф и грамматику из файла.

2023-05-08 16:49 UTC, Lsr248 commented on project/hellings.py
> +def hellings(graph: Graph, cfg: CFG) -> set:
Исправила замечения

2023-05-10 15:06 UTC, rustam-azimov approved these changes

2023-06-19 15:11 UTC, merged